language: node_js
node_js:
  - "10"

branches:
  only:
    - master

# deploy전에 실행할 명령어
before_deploy:
  - mkdir -p deploy
  - mv db.json deploy/db.json

deploy:
  - provider: s3
    access_key_id: $AKIASLVT2SVHI6C23LGB # Travis CI에서 설정한 AWS_ACCESS_KEY
    secret_access_key: $K/XQbbfZITCBPsw7MPb8mIylbwWbhrYO+S/+gr8Y # Travis CI에서 설정한 AWS_SECRET_KEY
    bucket: aws-lamba-chatbot-travisci # S3 bucket 명
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: deploy # S3로 올릴 디렉토리 대상 (before_deploy에서 생성함)
    acl: public_read
    wait-until-deployed: true
    on:
      repo: Edwardchung/chatbot # 저장소 이름
      branch: master

after_deploy:
  - echo "S3 업로드 끝났습니다."