language: node_js
node_js:
  - "10"

branches:
  only:
    - master
    
script: "node src/build.js"

before_deploy:
  - mkdir -p deploy
  - mv db.json deploy/db.json

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY 
    secret_access_key: $AWS_SECRET_KEY
    bucket: aws-lambda-chatbot-travisci 
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: deploy
    acl: public_read
    wait-until-deployed: true
    on:
      repo: Edwardchung/chatbot 
      branch: master

after_deploy:
  - echo "S3 업로드 끝났습니다."